### ISSUE TITLE
repository size is huge

### ISSUE THREAD

**Issue by Luap99** [containers/podman.io#107]
Cloning this repository took a long time. The repo already takes 196 MB disk space right now on my system.

The problem seems to be that the `.yarn` directory is committed with all the packages.

The upstream docs show which files can/should be ignored: https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored

Looks like the directory is not ignore since https://github.com/containers/podman.io/commit/35edaacad6372b7df569c31001b00a9ac6083335, given how big this grow in in just 5-6 weeks I say we really need to ignore this directory. It is not reasonable to expect contributors to pull such big repos.

**Comment by benoitf** [comment]
it depends if you want to be a `Zero-Installs` or not repository

**Comment by Luap99** [comment]
Why would I ever want this? It is clear that storing these javascript dependencies in a git repository is not viable in the long run. The size they add up is just insane. These things were just committed in the past few weeks. I can only imagine how the repo will grow quickly over gigabytes in size as git will store this "cache" forever.  As a contributor I am not going to pull down a gigabyte repository just to fix a typo or link.

Our over 5 year old podman repo is 234 MB in size and we do vendor dependencies there as well. To me it looks like this is not reasonably in the js ecosystem.

**Comment by Luap99** [comment]
> are you using --depth 1 when you're cloning repositories ? 

I do not, I am sure this would help as the history isn't that important for most people but still this shouldn't be necessary IMO.

**Comment by rhatdan** [comment]
I agree a cache should not be checked into the repo.
