### ISSUE TITLE
Missing links and landing spots for the meeting notes

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#112]
There are a number of meeting notes for the Podman Community and the Podman Community Cabal meeting on the old website, and there's not a landing spot or a link to them on the new page.

**Comment by cgiradkar** [comment]
Fixed here: https://github.com/containers/podman.io/issues/155, so closing the issue.
@TomSweeneyRedHat if this requires additional fixing, plz reopen this.
