### ISSUE TITLE
Release Announcements?

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#117]
I'm not finding a link to the release announcements.  We used to have them on Podman.io, I think they moved to Wordpress, but we ought to have a link somewhere on the site to them.  If the release announcements are now on Wordpress, the old ones should be moved from the old podman.io site.

**Comment by mairin** [comment]
We should do release announcements in a category ("Release Announcements"?) on the wordpress blog, then we can use the same wordpress hookup we already have in the "news" section on the front page to make a release announcements section but filter it to the "Release Announcements" category?

**Comment by TomSweeneyRedHat** [comment]
That would work for me.  I'm fine having the release announcements live anywhere, I just want a link to them from somewhere on the site.  It would probably be good to have a similar link for Podman Desktop.  They have been chunking their RA's under https://podman-desktop.io/blog.  It might make sense to have their RA's posted under a similar structure on https://podman-desktop.io just for symmetry's sake?

**Comment by cgiradkar** [comment]
Implement a widget on the front page to display the latest release announcement from https://blog.podman.io/ 
form a category to only fetch release announcements

**Comment by cgiradkar** [comment]
A simple fetch from `https://containersteam.wpengine.com/?s=release` returns a html page which can be shown in an iframe, but if the iframe is displayed on the home page, it really makes a mess visually. the nearest way to still display the top 10 RAs on homepage is to get the page's html and trim it (which I did) but there are still UI elements misbehaving in terms of size.
Having said that, an alternate way to show RAs is by creating another blog category (which is supported by docusaurus out of the box) and keep on manually updating the markdown files like we do for the meeting notes. Biggest pain point: manual updation.
Let me know your thoughts @TomSweeneyRedHat @mairin

**Comment by TomSweeneyRedHat** [comment]
I'd vote for the manual updating, I'm fine doing that as long as I know what to update.
