### ISSUE TITLE
Need better 404

### ISSUE THREAD

**Issue by mairin** [containers/podman.io#124]
We have cute sad seal art, we should use it :grin:

![Screenshot from 2023-05-13 15-55-18](https://github.com/containers/podman.io/assets/799683/b9a2a481-e97f-42f7-8b36-d867fccf15d5)

**Comment by afbjorklund** [comment]
The text is misleading, as well. It is **not** the original link that is broken, it is all the broken old podman.io URLs

* #125

**Comment by cgiradkar** [comment]
![localhost_3000_sss](https://github.com/containers/podman.io/assets/135707592/2c718cfa-6347-43b9-920f-89061be3f809)
Added a seal image to look like this
@mairin please review the PR at #207

**Comment by afbjorklund** [comment]
Seems like now even the seal is missing: (relative vs. absolute link?)

![seal-missing-404-page](https://github.com/containers/podman.io/assets/10364051/89fbfbe1-2f9d-465a-9d1d-49c96461eec8)


https://github.com/containers/podman#podman-former-api-varlink

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar ?

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat fixed it here: https://github.com/containers/podman.io/pull/217

**Comment by TomSweeneyRedHat** [comment]
@afbjorklund it looked happier to me after #217.  Could you reverify please and TYVM for the eagle eye!  Now to get those old post back up.
