### ISSUE TITLE
Old blog article link is broken

### ISSUE THREAD

**Issue by phlogistonjohn** [containers/podman.io#125]
I can no longer access blog articles like https://podman.io/blogs/2021/10/11/multiarch.html directly (a link I have bookmarked).
Instead I had to use http://web.archive.org/web/20230405171635/https://podman.io/blogs/2021/10/11/multiarch.html to refer to the articles content.

Ideally, "[cool urls don't change](https://www.w3.org/Provider/Style/URI)", so it would be nice if the new site could retain the old working urls (even if via redirect) so that useful content like the above continues to be easily available.

I hope this suggestion is helpful, I didn't see any open issues for this topic. Thanks!

**Comment by afbjorklund** [comment]
Same with https://podman.io/blogs/2020/01/17/podman-new-api.html from the home page / README

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar PTAL

**Comment by cgiradkar** [comment]
Sure @TomSweeneyRedHat , I will restore old blog article links

**Comment by cgiradkar** [comment]
import old podman.io/blogs to blog.podman.io && redirect vice-versa

**Comment by cgiradkar** [comment]
Helpful issue: [(v2) Automatic redirect of old docs #2843](https://github.com/facebook/docusaurus/issues/2843)

**Comment by cgiradkar** [comment]
The blog which can be accessed at [http://web.archive.org/web/20230405171635/https://podman.io/blogs/2021/10/11/multiarch.html](http://web.archive.org/web/20230405171635/https://podman.io/blogs/2021/10/11/multiarch.html) should also have been present at [https://containersteam.wpengine.com/archives/](https://containersteam.wpengine.com/archives/), but  is not. @TomSweeneyRedHat @cevich  @mairin  do we know where all the blogs dating to 2021 (as the link suggests) are stored?

**Comment by afbjorklund** [comment]
On the theme of breaking URLs, it was renamed (twice, old + old)

https://github.com/containers/podman.io_old/tree/main/old/_posts

**Comment by cevich** [comment]
Should be in the podman.io repo. history no?

**Comment by TomSweeneyRedHat** [comment]
no.  It's likely in https://github.com/containers/podman.io_old

**Comment by cevich** [comment]
Thanks Tom.  That would explain why I couldn't find anything when I went looking a few minutes ago :laughing:

**Comment by mairin** [comment]
@cgiradkar do you think we could run smtg like this on them? 

https://wordpress.org/plugins/import-markdown/

**Comment by cgiradkar** [comment]
> no. It's likely in https://github.com/containers/podman.io_old

@TomSweeneyRedHat There are no blogs [https://github.com/containers/podman.io_old/tree/main/old/blogs](https://github.com/containers/podman.io_old/tree/main/old/blogs)

**Comment by afbjorklund** [comment]
https://github.com/containers/podman.io_old/blob/main/old/_posts/2021-10-11-multiarch.md

**Comment by cgiradkar** [comment]
> https://github.com/containers/podman.io_old/blob/main/old/_posts/2021-10-11-multiarch.md

Thanks for the help @afbjorklund

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar the /blogs directory had just a simple bit of code that created the list of blogs and created links for each.  The actual blogs all live in the `_posts` directory as Anders noted:  https://github.com/containers/podman.io_old/tree/main/old/_posts

**Comment by TomSweeneyRedHat** [comment]
And be warned, the _posts directory also contained the release announcements.  The difference is the tag at the top of each md file.  `[blogs]` for blogs, and I think `[releases]` for release announcements.

**Comment by cgiradkar** [comment]
> And be warned, the _posts directory also contained the release announcements. The difference is the tag at the top of each md file. `[blogs]` for blogs, and I think `[releases]` for release announcements.

Got it @TomSweeneyRedHat . Do you want me to create another tab for release announcements?

**Comment by TomSweeneyRedHat** [comment]
I thought the RA's had already been backported and placed somewhere.  If not, then yes, please do if you can.  @cgiradkar

**Comment by cgiradkar** [comment]
@mairin I have added the blogs to the new site and the looks are not so promising: 
![localhost_3000_blog](https://github.com/containers/podman.io/assets/135707592/45264e30-d929-4acf-b483-4eb690169d85)
maybe the markdown format used earlier and used by Docusaurus are not compatible.
@TomSweeneyRedHat do you have any suggestions for beautifying the blogs list by changing some markdown syntax?

**Comment by cgiradkar** [comment]
Also, the tags field in the blogs markdown file is an array according to Yaml and it will fail the build for newer blogs if not configured properly

**Comment by TomSweeneyRedHat** [comment]
Sorry @cgiradkar look/feel is not my strong point.   I'd lean on @mairin

**Comment by mairin** [comment]
Hey @cgiradkar - I need a little more context on this. Can you give me a full screenshot (or let me know what branch I can check out locally to see?)

**Comment by cgiradkar** [comment]
@mairin you can check this out: https://github.com/containers/podman.io/pull/198
It also contains the changes made, if it's still unclear, then we can discuss it over a g-meet

**Comment by mairin** [comment]
@cgiradkar and I are chatting about this now... 

1. Lines like this appearing wholesale in the imported blog posts are Jekyll and we should convert or strip them out:

`By {{ author.display_name }} [GitHub]([https://github.com/{{](https://github.com/%7B%7B) author.github }})
`
2. Images aren't displaying, just their alt tags. It would be nice to figure out how to convert the image tags from Jekyll to something markdown understands and can be rendered on the page.

I am confused/concerned about the bigger picture here:

Are we restoring old blog posts under their own paths on podman.io, and also including newer blog.podman.io posts in a unified "Development Blog" section on the website? Or is the "Development Blog" entry in the nav / header just temporary so these blog posts can be viewed while this conversion work is being done? 

I understand the reason to restore the old posts via docusaurus on podman.io is to restore the old links, but its a bit weird to have the blog content split between two places and I was thinking we would have imported the old content into Wordpress and set up redirects via routing on the podman.io config? The downside of the approach of having two locations is no unified search across posts, categories being split depending on which site you're viewing from / etc. What am I missing here?

**Comment by TomSweeneyRedHat** [comment]
I'm fine with whatever the easisest/fastest solution is.  We have just had a number of pings saying "this post isn't there anymore", and I'd like to get them there.  Any new posts should go to the Wordpress section of the site.  I'm fine with just getting the old posts into their own section here, behind a readme.md or something saying they're archived, just so we can reestablis the links.  I'm also fine converting them into Wordpress and doing redirects.  I don't have a good solution for that last part off the top of my head, but can probably gronk it out.

So what ever is quickest and easiest.  I'm not looking for style points on these old posts, just availability.

**Comment by afbjorklund** [comment]
If the links from the podman repository main [readme](https://github.com/containers/podman#readme) were not broken, that would be an improvement...

~~https://podman.io/images/podman-hello.jpg~~

EDIT: Image removed https://github.com/containers/podman/commit/3fc7c42e187f284c6d377204ac3f89c382265d5b

~~https://podman.io/blogs/2020/01/17/podman-new-api.html~~

**Comment by TomSweeneyRedHat** [comment]
The redirect link needs to still happen. I'll try to make that so today.

**Comment by cgiradkar** [comment]
Closing as marked completed here: https://github.com/containers/podman.io/issues/189#issuecomment-1761702136

**Comment by TomSweeneyRedHat** [comment]
And it looks like I did the necessary redirect link a while back and forgot about it.   The latest changes from @cgiradkar have restored all the old blogs that I tried to get to.  Please report any that you find that are still doing the 404 thing.
