### ISSUE TITLE
Error in the Kubic project link 

### ISSUE THREAD

**Issue by nluaces** [containers/podman.io#143]
Hi, 
There is a mistake in the Kubic project link referenced in the documentation:

https://github.com/containers/podman.io/blob/ec889dcd9d97e3bc8ba973d2f44400882140ba1c/docs/installation.md?plain=1#L98

When downloading the release key, the following curl returns a 404 status.
```
curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key 
curl: (22) The requested URL returned error: 404
```

This URL is the one that seems to work: 
```
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key 
```

**Comment by cgiradkar** [comment]
@nluaces can you try again. I just tried to reproduce the bug, I am getting expected response.

**Comment by nluaces** [comment]
@cgiradkar it is working for me now. I guess this issue can be closed. 
Thank you.

**Comment by cgiradkar** [comment]
Closing issue as it can't be reproduced.
