### ISSUE TITLE
Add blog RSS feed link

### ISSUE THREAD

**Issue by cevich** [containers/podman.io#148]
Apparently it's available at [https://blog.podman.io/feed/](https://blog.podman.io/feed/) but there's no link mentioning this anywhere.  Maybe include this in the page footer?

**Comment by cgiradkar** [comment]
We are in a process of migrating blogs to podman.io/blog and hence the RSS feed xml should be generated and used. The link [https://blog.podman.io/feed/](https://blog.podman.io/feed/) is maintained and generated by blog.podman.io.
I think we should use the former one and it is supported by Docusaurus.
If we're going through the pathway of using Docusaurus to generate the xml, this issue depends on #198 
fyi @cevich @mairin

**Comment by mairin** [comment]
Hi @cgiradkar I don't think there is any plan to shut down blog.podman.io, the idea was to use the RSS from blog.podman.io to display those blogs on podman.io/blog. Am I misunderstanding this issue?

**Comment by cgiradkar** [comment]
@mairin We wanted to bring up all the older blog posts because the URLs changes when we moved to blog.podman.io. Hence, we should use RSS feed from the local blogs
