### ISSUE TITLE
Documentation partially obsolete | section "Fedora"

### ISSUE THREAD

**Issue by Ricky-Tigg** [containers/podman.io#153]
Hello. Current instructions and information at https://podman.io/docs/installation are became partially obsolete.
- Edition _35_ of Fedora is out-of scope since it reached EOL. Podman's **stable version channel** is covered in Fedora's repositories, thus officially shipped, though not always with latest versions.
- At Copr, rhcontainerbot's _podman4_ repository doesn't exist any more. It can reasonably be supposed that it used to cover the stable version channel. The _main_ channel is covered by the _podman-next_ repository. That should be a viable option for installation source in order to be in position to select the option "_yes_" associated to _Upstream latest release_ in the issue template of the present repository, as it contains the code of the latest stable version.

```
$ dnf --installed rq --qf '%{version} %{from_repo}' podman
4.6.0~dev copr:copr.fedorainfracloud.org:rhcontainerbot:podman-next
```

**Comment by Luap99** [comment]
Thanks for the report, I created https://github.com/containers/podman.io/pull/154 to remove this paragraph.
