### ISSUE TITLE
Building from scratch | section "Fedora"

### ISSUE THREAD

**Issue by Ricky-Tigg** [containers/podman.io#157]
Hello. At https://podman.io/docs/installation#building-from-scratch, which seems to apply to Fedora, the packages _go_, _iptables_ and _pkgconfig_ do not exist in Fedora's repositories. However their equivalent could exist; here are those that could be such ones:
```
$ dnf --installed rq --qf '%{name} | %{summary}' golang iptables-libs pkgconf
golang | The Go Programming Language
iptables-libs | libxtables and iptables extensions userspace support
pkgconf | Package compiler and linker metadata toolkit
```
Of course that would require confirmation from one of yours. If confirmed, the whole amount of  packages required for installation could be selected as follows (compacted variant):
```
$ sudo dnf -y install {btrfs-progs,device-mapper,glib2,glibc,gpgme,libassuan,libgpg-error,libseccomp,libselinux}-devel \
conmon containernetworking-plugins containers-common crun git glibc-static golang golang-github-cpuguy83-md2man iptables-libs make pkgconf
```
It is unclear whether the installation of the packages mentionned as part of the installation command that follows the comand text `make package-install` must be operated before the execution of that command.

**Comment by cgiradkar** [comment]
@Luap99 need more clarification here

**Comment by Luap99** [comment]
@Ricky-Tigg I am not sure why you say these do not exist?
```
$ sudo dnf install go iptables pkgconfig
Last metadata expiration check: 0:00:20 ago on Fri 07 Jul 2023 10:02:50 CEST.
Package golang-1.19.10-1.fc37.x86_64 is already installed.
Package iptables-legacy-1.8.8-5.fc37.x86_64 is already installed.
Package iptables-nft-1.8.8-5.fc37.x86_64 is already installed.
Package pkgconf-pkg-config-1.8.0-3.fc37.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
```

All of them install just fine, sure they are alias but that doesn't matter. The dnf install command is valid as is and in case of iptables it doesn't make sense to switch it as there are two variants and it i up to package manger to choose the right one not us.

**Comment by Ricky-Tigg** [comment]
I had executed '`dnf -q list go iptables pkgconfig`' to serve my investigation. At the time, an **empty output** was produced. The installed version of DNF was **4.14.0**. With the version **4.16.1** of DNF now installed, the output is no longer empty! Instead **are queried packages whose names are not exact matches** which illustrates a faulty behavior and thus indicates an issue.

Then in the version 4.14.0, the intended behavior was still observable, that is _query packages whose names are exact matches_. According to the output resulting from the command you run, it suffers from this same issue, since **none of the packages selected by DNF match those queried** for installation. I shall dully report it.

**Comment by Ricky-Tigg** [comment]
Output against which I created this report:
```
$ dnf -q list go iptables pkgconfig
Error: No matching Packages to list
```
`dnf install` takes `<spec>`_(!)_ as argument. `dnf list` takes only `<package-file-spec>` which is similar to `<package-spec>`, except _provides_ matching is not performed. Therefore `<package-file-spec>` is matched only against NEVRAs and _file provides_. Then in your command, _provides_ is implied therefore `install` is effective while in my command it isn't , so is not effective. Yet in the current instructions, it can't be deducted that expected to install are those packages installed along with your very  command. We can close if you believe they are explicit enough.

(!) It can be `<package-spec>`, `@<module-spec>`, or `@<group-spec>`.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 any thoughts?

**Comment by lsm5** [comment]
@Ricky-Tigg `package-install` target is broken right now. I'm currently working on it.

Also, what version of Fedora are you using? Looks like different dnf versions might produce different outputs, especially dnf5. 

```
dnf -q list go iptables pkgconfig
Installed packages
golang-bin.x86_64      1.20.5-1.fc39 fedora
iptables-nft.x86_64    1.8.9-4.fc39  fedora

Available packages
gcc-go.x86_64          13.1.1-4.fc39 rawhide
iptables-legacy.x86_64 1.8.9-4.fc39  rawhide
```

If it helps, we can specify actual package names or add additional cases for different dnf versions.

**Comment by Ricky-Tigg** [comment]
```
$ cat /etc/redhat-release
Fedora release 38 (Thirty Eight)
$ dnf --version | head -1
4.16.1
```

**Comment by lsm5** [comment]
> ```
> $ cat /etc/redhat-release
> Fedora release 38 (Thirty Eight)
> $ dnf --version | head -1
> 4.16.1
> ```

@Ricky-Tigg thanks. https://github.com/containers/podman.io/pull/174 should just work (TM) as it's being continuously tested with all active versions of fedora and centos stream. That PR depends on https://github.com/containers/podman/pull/19214 which should be going in anytime now.

**Comment by Ricky-Tigg** [comment]
Lucky RPM-users; Thank you.
