### ISSUE TITLE
Podman Hello not found

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman.io#168]
https://podman.io/images/podman-hello.jpg

https://github.com/containers/podman/tree/v4.5.1#podman-hello

Maybe it can be restored from the "backup" ?

https://github.com/containers/podman.io_old/blob/main/old/images/podman-hello.jpg

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat can we remove the link to podman-hello in README as it is not needed really.

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar as it was just an Easter Egg that I added at one point, I'm fine with removing the link.  I'll keep this open until a PR to do so is merged.
