### ISSUE TITLE
Markdown source code shown at https://podman.io/community

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman.io#185]
On the web page

https://podman.io/community

I see this text

```
It is also used to make announcements about
Podman and the other projects in the [Containers repository
on GitHub](https://github.com/containers).
```

I assume 

`[Containers repository on GitHub](https://github.com/containers)`

is Markdown source code that should have been translated to HTML.

I'm using this web broswer:
```
$ rpm -qa | grep google-chrome
google-chrome-stable-115.0.5790.110-1.x86_64
```

**Comment by rhatdan** [comment]
@mairin @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
@cgiradkar PTAL

**Comment by cgiradkar** [comment]
@eriksjolund can you try again as the bug is not reproducing on latest podman.io.
