### ISSUE TITLE
Broken link for old blog

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#189]
Gabriella Necasova reported that this link: https://podman.io/blogs/2019/09/26/podman-in-hpc.html is no longer working.  I suspect many, if not all of the old blog post links are not working.  @cgiradkar can you PTAL?

**Comment by cgiradkar** [comment]
Sure @TomSweeneyRedHat , there's another issue like this : https://github.com/containers/podman.io/issues/125
will club them.

**Comment by afbjorklund** [comment]
> I suspect many, if not all of the old blog post links are not working.

It is even worse, they blame the user instead of fixing the website...

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat we can close this after adding a replacement from blog --> blogs in the url. Currently Docusaurus supports /blog endpoint out of the box.

**Comment by cgiradkar** [comment]
> @TomSweeneyRedHat we can close this after adding a replacement from blog --> blogs in the url. Currently Docusaurus supports /blog endpoint out of the box.

On another note, I have found out a way (not provided in documentation) to alter the base route path for a blog. So including the altered path in a new PR.

**Comment by TomSweeneyRedHat** [comment]
I'm seeing a blog and blogs endpoint in our DNS settings, and the old blogs seem to be resolving themselves now.  Thanks @cgiradkar !

**Comment by GabiNecasova** [comment]
Thank you! :smile:
