### ISSUE TITLE
Formatting issue in the podmansh blog post. Two terminal lines shown on one line.

### ISSUE THREAD

**Issue by eriksjolund** [containers/podman.io#194]
My web browser Google Chrome version 116.0.5845.96 (Official Build) (arm64) shows some commands in the web page

https://blog.podman.io/2023/08/podman-v4-6-introduces-podmansh-a-revolutionary-login-shell/

like this:

```
# useradd -s /usr/bin/podmansh lockedu# grep lockedu /etc/passwd
lockedu:x:4008:4008::/home/lockedu:/usr/bin/podmansh# USER_ID=$(id -u lockedu)
```

I would have expected the commands to be shown like this

```
# useradd -s /usr/bin/podmansh lockedu
# grep lockedu /etc/passwd
lockedu:x:4008:4008::/home/lockedu:/usr/bin/podmansh
# USER_ID=$(id -u lockedu)
```

**Comment by rhatdan** [comment]
@lsm5 @TomSweeneyRedHat PTAL

**Comment by lsm5** [comment]
@eriksjolund thanks for the report. Fixed now. Reopen issue if it still doesn't look right.
