### ISSUE TITLE
Wrong link for community meeting

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman.io#210]
On https://podman.io/community

Both links go the _same_ URL, Podman Community Meeting

https://meet.google.com/ieq-pxhy-jbh

There is a different URL, for the Podman Community Cabal

https://meet.google.com/xrq-uemd-bzy

**Comment by cgiradkar** [comment]
This can be fixed by integrating google calendar APIs to get the link of latest meeting/Cabal. Will need to delve deeper before coming to a strategy.

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat can we close this issue?
