### ISSUE TITLE
Contributor Guidelines footer link on blog.podman.io broken

### ISSUE THREAD

**Issue by sob** [containers/podman.io#226]
Hi - I couldn't find where this is generated from to send a pull request, but the Contributor Guidelines link in the footer of blog.podman.io is broken and pointed to:

`"http://we%27re%20a%20collection%20of%20open%20source%20tools%20that%20create%2C%20configure%2C%20and%20work%20with%20containers./".
`

Thanks!

**Comment by TomSweeneyRedHat** [comment]
@sob Thanks for the eagle eye and issue.  @cgiradkar PTAL

**Comment by cgiradkar** [comment]
@mairin do you know where blog.podman.io is hosted?

**Comment by mairin** [comment]
I do! It's hosted with wpengine and infra wise admined by OSPO.... I have
admin to the wordpress application.

**Comment by cgiradkar** [comment]
fixed
