### ISSUE TITLE
https certificatye gone

### ISSUE THREAD

**Issue by lesar** [containers/podman.io#238]
You have security problem: your https certificate don't work today 2023-11-13  
on [https://www.podman.io/](https://www.podman.io/)   
I have not see what are you using but on my web site I use
I use [https://certbot.eff.org/](certbot) to get update [https://letsencrypt.org/](letsencrypt) https certificate  

I hope this post is useful

**Comment by benoitf** [comment]
Thanks @lesar 

it looks like the good URL is https://podman.io/

I've reached the GitHub support

**Comment by benoitf** [comment]
here is the support answer

> Thanks for contacting GitHub Support! Having a look at some errors here on my end and I can see the following:
> Alternate Domain CNAME record - Does not point to user pages domain
> Looking at [WhatsMyDNS](https://www.whatsmydns.net/#CNAME/www.podman.io) it appears that www.podman.io is pointing to podman.io, but for GitHub Pages to issue a certificate, it would need to be pointed to the user/org username on our end to work as expected. Would it be possible for you to log into your DNS registrar and update the CNAME value to point to containers.github.io instead of podman.io?
> Once that's done and propagated, head over to the repositories settings and allow it a few moments to perform the DNS verification. Once that's done it should grant a new certificate within the hour. If it doesn't, feel free to shoot me a message here and we can re-roll the certs if that's required.

so if someone having DNS access to podman.io could update `www` on `podman.io` to redirect to `containers.github.io.`  instead of `podman.io.`

**Comment by lesar** [comment]
Ok I have not try without www.  
so is only that www is not been add.
Thank you for the answer.

**Comment by TomSweeneyRedHat** [comment]
@lesar thanks for the heads up.  As luck would have it, I received a similar report late on Friday.  I'm pretty sure it's a DNS issue, as @benoitf (thanks!) pointed out.  I'll try to parse some time today to correct that, but it might take a few days to bubble.  As noted, https://podman.io should work just fine and is secured with a certificate.
