### ISSUE TITLE
Donate towards development of Podman

### ISSUE THREAD

**Issue by chrishobcroft** [containers/podman.io#261]
Issue here is that there is no obvious way to contribute capital to podman rn.

As a user of this website, I would like to be able to contribute financially to this project, which is providing my project with huge utility - it's a missing link, and a valuable one at that.

# Proposal.

Podman must have a core team, and a broader community. You could create a smart contract wallet on an EVM, and receive erc20 stablecoins, where the core team and the community can collectively agree how to spend any money. It would be like a Podman jurisdiction, with governance, finance, coordination. Then ultimately you could publish the address of the Podman onchain treasury, for receiving donations to your wallet on an EVM network.

**Comment by rhatdan** [comment]
We do not take contributions.
