### ISSUE TITLE
Podman version 4.9.3 is missing, currently still listing 4.9.2

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman.io#284]
Probably should be part of the release procedure ?

```
export const LATEST_VERSION = '4.9.2';
export const LATEST_DESKTOP_VERSION = '1.7.1';
```

https://github.com/containers/podman/releases/tag/v4.9.3
https://github.com/containers/podman-desktop/releases/tag/v1.8.0

Seems that 1.8.0 is still in "pre-release", unannounced

**Comment by benoitf** [comment]
For Podman Desktop it's part of the process release when the release is promoted to a stable release

**Comment by benoitf** [comment]
looks like for 4.9.3 there is a pending PR https://github.com/containers/podman.io/pull/283

**Comment by benoitf** [comment]
fixed now by the merge of https://github.com/containers/podman.io/pull/283

**Comment by afbjorklund** [comment]
The link goes to `v5.0.0-rc6`, anyway (not `v4.9.3`)

https://github.com/containers/podman/releases

Have to scroll down past Pre-release, for Latest

But it is not as "bad" as the 2,748 PD releases ;-)
