### ISSUE TITLE
Release blog is not updated for version 4.4.0 and up

### ISSUE THREAD

**Issue by afbjorklund** [containers/podman.io#316]
https://podman.io/release/

* https://podman.io/release/2022/10/22/podman-release-v4.3.0

* https://podman.io/release/2022/08/17/podman-release-v4.2.0

* https://podman.io/release/2022/05/09/podman-release-v4.1.0

* https://podman.io/release/2022/02/22/podman-release-v4.0.0

* https://podman.io/release/2021/08/31/podman-release-v3.3.0

* ~~podman-release-v3.2.0~~

* https://podman.io/release/2021/04/02/podman-release-v3.1.0

* https://podman.io/release/2021/02/11/podman-release-v3.0.0

Only the Development blog:

https://blog.podman.io/2024/03/podman-5-0-has-been-released/

**Comment by Luap99** [comment]
all new blog posts moved to https://blog.podman.io/ we do not create new posts for podman.io directly to my understanding. As of why not all release have post I don't know.

@mheon @ashley-cui

**Comment by afbjorklund** [comment]
Linked directly to the release notes on GitHub instead....

https://github.com/containers/podman/releases/tag/v5.0.0

**Comment by afbjorklund** [comment]
You might want to add a link / comment on the top of the page?

Something like "This page has not been updated since 2022"

They only seem to be used in the initial announcement:

https://podman.io/blogs/2018/09/10/welcome

----

> We therefore welcome you to the new websites, [buildah.io](https://buildah.io/) and [podman.io](https://podman.io/) where you will find news, announcements, and more around the respective projects.
>
> To start it up, check out the new [Blogs](https://podman.io/blogs) and [Releases](https://podman.io/releases) sections on the site.

https://podman.io/blogs/2022/12/07/new

**Comment by afbjorklund** [comment]
@TomSweeneyRedHat guess it stopped?

* https://github.com/containers/podman.io/issues/117

**Comment by afbjorklund** [comment]
It was 4.9 through 5.1 that were the exceptions, the rest _were_ tagged OK (with "releases") in the _new_ blog:

https://blog.podman.io/category/releases/

* **https://blog.podman.io/2024/08/podman-5-2-release-and-it-brings-friends-along-too/**

* ~~5-1~~

* ~~5-0~~

* ~~4-9~~

* https://blog.podman.io/2023/11/podman-v4-8-released/

* https://blog.podman.io/2023/09/new-podman-release-v4-7-0/

* https://blog.podman.io/2023/07/podman-v4-6-released/

* https://blog.podman.io/2023/04/new-release-podman-v4-5/

* https://blog.podman.io/2023/02/podman-v4-4-buildah-v1-29-released/
