### ISSUE TITLE
Building from source - links to configuration files are broken

### ISSUE THREAD

**Issue by MillQK** [containers/podman.io#318]
Links in this section https://github.com/containers/podman.io/blob/main/docs/installation.md#add-configuration lead to page with 404

**Comment by afbjorklund** [comment]
The files from https://src.fedoraproject.org/rpms/containers-common

https://src.fedoraproject.org/rpms/containers-common/raw/main/f/registries.conf
https://src.fedoraproject.org/rpms/containers-common/raw/main/f/default-policy.json

Are now upstream in https://github.com/containers (common or **image**)

https://raw.githubusercontent.com/containers/image/main/registries.conf
https://raw.githubusercontent.com/containers/image/main/default-policy.json

---

See the original fedora packaging scripts:

https://src.fedoraproject.org/rpms/containers-common

There is a PR that addresses this issue:

* https://github.com/containers/podman.io/pull/312
