### ISSUE TITLE
“This page crashed”

### ISSUE THREAD

**Issue by mtrmac** [containers/podman.io#43]
Opening https://containers.github.io/website-new/ shows me

> This page crashed.
> undefined is not an object (evaluating 'e.path')

Happens to me on both Safari and Chrome on macOS, both in the primary session and private browsing. (Did not happen to colleagues testing simultaneously.)

**Comment by lilyx13** [comment]
@mtrmac were your colleagues also running MacOS?

Can you let me know if it's still happening today or tomorrow?

**Comment by TomSweeneyRedHat** [comment]
I believe the rest of us were using Chrome or Firefox on RHEL and Fedora, we did not have issues.

**Comment by mtrmac** [comment]
It is still happening.

In developer console, I see
```
TypeError: Cannot read properties of undefined (reading 'path')
    at h (1df93b7f.c3c6c36b.js:1:9991)
    at 1df93b7f.c3c6c36b.js:1:11704
    at r (900.47f3a219.js:1:231)
    at ii (main.60fde97d.js:2:300932)
    at qi (main.60fde97d.js:2:310450)
    at Ws (main.60fde97d.js:2:354031)
    at Rl (main.60fde97d.js:2:340335)
    at Al (main.60fde97d.js:2:340263)
    at Tl (main.60fde97d.js:2:340126)
    at vl (main.60fde97d.js:2:337113)
```

with the `h` function being
```js
       const h = ()=>{
            const e = g();
            return n.createElement("section", null, n.createElement("div", null, n.createElement("a", {
                href: e.path,
                className: "block rounded-t-md transition duration-150 ease-linear hover:bg-purple-700 hover:text-white hover:no-underline dark:hover:bg-purple-900"
…
```
where `g` is
```js
            return u.find((e=>e.id === window.navigator.userAgent.toLowerCase().split(" ").find((e=>e.includes("linux")))))
```

so… it seems attractive to guess that not using Linux might make a difference. (I don’t know enough about the site to understand where this JavaScript comes from or what its purpose is.)

I guess https://github.com/containers/website-new/blob/a2db125ca53a910a2abe081022c3831faaa8e60e/src/components/layout/HeroHeader/index.tsx#L24 might be related, although I don’t see how the three `includes` variants turned into one condition?

FWIW the `navigator.userAgent` is
`
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36'` in Chrome. and `"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15"` in Safari.

**Comment by lilyx13** [comment]
Ok that might be related to the OS detection for downloads on the home page. I think I have an idea

**Comment by lilyx13** [comment]
Ok I spoofed my user agent to be windows and I'm getting the same error. I should have a fix soon.

**Comment by lilyx13** [comment]
@mtrmac thank you so much for the dev console output.

**Comment by mtrmac** [comment]
https://containers.github.io/website-new/features and https://containers.github.io/website-new/get-started work.
