### ISSUE TITLE
Implement videos for Features page

### ISSUE THREAD

**Issue by mairin** [containers/podman.io#49]
SSIA // May not need alpha given zoom effect, but look into it

**Comment by mairin** [comment]
I don't think I'm gonna add alpha, it doesn't seem necessary in my test page. Right now the smallest format I can get is m4v, I can get edited videos down to about 700k.

**Comment by mairin** [comment]
OK, I have 2 of the 4 features with edited down video now.... first is like 500k, second is 800k. They gotta be cut down to less than 10s. The second has more compression too just to get the size down below 1MB. 

Screencast showing them in the mo-features2-video branch.

I don't really know how awesome a screencast video of a video playing in a web browser is gonna be, but I promise these are smooth IRL.

**Next steps**
- Gotta edit down short vids for podify + k8s deploy
- Build in image fallback for browsers that can´t play vids
- Want to do some kind of JS scroll-based auto-play / auto-stop and hide controls. @lilyx13 have you ever done this before? do you think there are any libraries we could pull in that might handle this stuff OOTB? 

[Screencast_08.05.23_17:00:03.webm](https://user-images.githubusercontent.com/799683/236934855-e7e6f51b-7f12-4ca6-b171-45087501d71b.webm)

**Comment by mairin** [comment]
If you wanna see the vids so far -

Containers: https://raw.githubusercontent.com/containers/podman.io/9f9387ed51252bbbad8effbcac0aba901a59476d/static/video/ui/containers.mp4

Images: https://github.com/containers/podman.io/raw/9f9387ed51252bbbad8effbcac0aba901a59476d/static/video/ui/images.mp4

**Comment by mairin** [comment]
Podify (509K, 22s)
https://github.com/containers/podman.io/raw/f374c73a97da6202496e95c337849ba226c79a6d/static/video/ui/podify.mp4

**Comment by slemeur** [comment]
👍

**Comment by mairin** [comment]
This will be addressed in:
https://github.com/containers/podman.io/pull/68

(currently under review)

**Comment by mairin** [comment]
closing, merged 🦭   🥳

**Comment by TomSweeneyRedHat** [comment]
Hmm, I'm surprised the "Will Address #49" in the PR didn't auto-close this.  Next time @mairin, could you try "Addresses: #{Issue}" or "Fixes: #{Issue}"  all by itself on a line in the PR description or in a comment and see if that auto-closes the issue?

**Comment by mairin** [comment]
@TomSweeneyRedHat sure. I was pretty befuddled by this because in other repos I've only needed to just mention the ticket in the PR or vice versa and they get linked.
