### ISSUE TITLE
Podman Desktop under features section is not clickable

### ISSUE THREAD

**Issue by preethit** [containers/podman.io#52]
It would be nice to be able click on Podman Desktop under Features section to navigate to Podman Desktop website.

**Comment by mairin** [comment]
This is a great idea, thanks @preethit I will fix this.

**Comment by mairin** [comment]
Thanks for the suggestion! 🦭 🎉  Closing as fixed! 

![Screenshot from 2023-05-12 00-47-59](https://github.com/containers/podman.io/assets/799683/6d1b3113-1c9c-4f5b-a956-5f5526a10993)
![Screenshot from 2023-05-12 00-47-52](https://github.com/containers/podman.io/assets/799683/01e59643-9232-41a9-9ea6-25a378539503)
