### ISSUE TITLE
Missing getting started installation page.

### ISSUE THREAD

**Issue by paviln** [containers/podman.io#53]
From the page [podman_tutorial](https://podman.io/docs/tutorials/podman_tutorial), the section link of _For installing or building Podman, please see the_
 [/getting-started/installation](https://podman.io/getting-started/installation) gives: 
  Page Not Found
  We could not find what you were looking for.
  Please contact the owner of the site that linked you to the original URL and let them know their link is broken.

**Comment by mairin** [comment]
This is meant to replace it:
https://podman.io/get-started

But I notice there's a block missing there. So we should fix that for sure.

**Comment by mairin** [comment]
(And maybe set up a redirect too?)

**Comment by lilyx13** [comment]
This should be fixed. I made an installation.md file and moved the install info from the old page into it and routed the links.
