### ISSUE TITLE
Podman Community Meetings buttons non-functional

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#54]
The Join Meeting and Meeting Agenda buttons for the Community meeting and the Cabal are not colorized appropirately and don't go anywhere.  From slack discussion:

For the "Join Meeting" button url, in both cases: https://meet.google.com/ieq-pxhy-jbh

meet.google.commeet.google.com
[Meet](https://meet.google.com/ieq-pxhy-jbh)
Real-time meetings by Google. Using your browser, share your video, desktop, and presentations with teammates and customers.
[4:10](https://redhat-internal.slack.com/archives/D04KF2DU347/p1683317432201759)
Meeting Agenda for the Cabal: https://hackmd.io/gQCfskDuRLm7iOsWgH2yrg?both

hackmd.iohackmd.io
[Podman Community Cabal Agenda - HackMD](https://hackmd.io/gQCfskDuRLm7iOsWgH2yrg?both) (108 kB)
https://hackmd.io/gQCfskDuRLm7iOsWgH2yrg?both

[4:14](https://redhat-internal.slack.com/archives/D04KF2DU347/p1683317641856439)
Meeting agenda for the Community Meeting had been https://podman.io/community/meeting/agenda/index.html which was an index.md tfild that I updated.  Did that get transitioned?  (https://github.com/containers/podman.io_old/blob/main/old/community/meeting/agenda/index.md)

**Comment by lilyx13** [comment]
Fixed with #67
