### ISSUE TITLE
Podman links not working on features page

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#56]
The links under "Getting to know Podman" don't seem to be working on https://podman.io/features.  This includes the quicstart guie, Troubleshooting, documentation and the issue tracker.  

Also, the "Jon Podman's Community" has no links to click on to get info on things like Discord, IRC, meetings, etc.

**Comment by TomSweeneyRedHat** [comment]
Same trouble further down the page for the "Installation Instructions", "Documenation", and "Podman Troubleshooting" instructions.

**Comment by TomSweeneyRedHat** [comment]
Lastly, the link in the purple banner at the bottom of the page all work, however they disappear when you hover over them.

**Comment by lilyx13** [comment]
These should be good now and the disappearing links should be gone with #69
