### ISSUE TITLE
Get Started Page issues

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#57]
First one is a suggestion.  Near the top you say, "For more details, you can review the manpages:"  The man pages are on line at: https://docs.podman.io/en/latest/Commands.html  IDK if you want to add a link or not to them.

**Comment by TomSweeneyRedHat** [comment]
The "Troubleshooting guide" on the page goes no where.

**Comment by lilyx13** [comment]
These issues have been resolved with #67. I'll close but if there are more issues we can reopen and follow up.
