### ISSUE TITLE
Development Blog link

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#60]
The link for the development blog at the top of the page opens a new tab rather than going to the page in the current tab.  IDK if that's by design or not, but I'd rather that it just stayed in the same tab.  My old-style opinion, probably worth $.02

**Comment by lilyx13** [comment]
Ah the reason for the blog opening in a new tab was because it goes to a separate domain without a built in way to get back. @mairin what are your thoughts? should the link open in a new tab or same tab? I'm fine with doing it either way.

**Comment by lilyx13** [comment]
Will be resolved with #69 merge
