### ISSUE TITLE
GitHub link at top of page.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [containers/podman.io#61]
The link for GitHub at the top of the page opens a new tab rather than going to the page in the current tab. IDK if that's by design or not, but I'd rather that it just stayed in the same tab. My old-style opinion, probably worth $.02

**Comment by TomSweeneyRedHat** [comment]
I'll leave it to you two to decide about the tab thing for this and the other one.  However, back when the dinosaurs were still roaming the earth, I was doing some web page design/work and got ripped pretty badly for opening up new windows instead of staying within the tab.  But it could have been this person's whacky thinking too.

**Comment by lilyx13** [comment]
will be updated after the build from #69
