### ISSUE TITLE
Page GettingStarted -> Installation does not exist

### ISSUE THREAD

**Issue by Vespasian** [containers/podman.io#64]
https://podman.io/getting-started/installation linked from https://podman.io/docs/tutorials/podman_tutorial
errors out

**Comment by vsoch** [comment]
+1 - I came here to say this! I did a good search for the install, clicked on the link, and it was a 404. And then I did the following:

 - Went to the main root -> "Getting Started"
 - There was no Install section of that. It assumes I have it installed
 - There is also no search, so I can't even search for the "install" term
 - There is no obvious installation tutorial either

From a user standpoint coming to the docs, my frustration level is 10/10. Please fix this asap!

**Comment by krwu** [comment]
+1

I reinstalled one of my VPS and want to try podman instead of docker, but I failed at the very first step: "Installing podman by following its official guide".

**Comment by Luap99** [comment]
I agree due the new website move most links are just broken. I really would love if we could redirect all old links to the correct new places if necessary.  See https://containers.github.io/podman.io_old/old/getting-started/installation for the old site. I don't understand why you moved everything under a `old` directory there, @TomSweeneyRedHat?

So far I did not find a replacement for the old installation instructions on the new site so we definitely have to add this back somewhere. 

cc @containers/podman-maintainers @lilyx13 @mairin

**Comment by TomSweeneyRedHat** [comment]
Thanks for the issue reports.  We'll track down the issue and get things straightened out.

**Comment by lilyx13** [comment]
Fixing this now. links will be updated shortly

**Comment by lilyx13** [comment]
should be good after #67.

**Comment by Luap99** [comment]
Over the whole internet? Sure we can update the links in our repos but the main problem is the link is out there somewhere, blogs post, bookmarked by users, etc... we cannot just "update them".
I have no problems with having a new location but the old link should be redirected to the new one. I am not familiar with the docusaurus but in HTTP terms all we need is a HTTP 301 redirect. If you do not have time I can look into that, this is important to me.

**Comment by Luap99** [comment]
https://docusaurus.io/docs/docusaurus-core#redirect looks relevent

**Comment by TomSweeneyRedHat** [comment]
As @Luap99 the links are all over the internet, we need to get them back if they're not already.  That was what I was trying to do yesterday, had issues, and pinged you in slack about them.

@Luap99 , I moved everything in the old site to live under the "old" directory to make sure that someone didn't merge something in that repo (github.com/containers/podman.io_old) and then accidentally have everything for the new page be overwritten when a PR was merged.  I had hoped that all the pages would pop up under podman.io/old for easier reference/accessibility, but that failed and I've not had time to track that down yet.

**Comment by lilyx13** [comment]
In #92 I merged a change that will at least take care of this for pages searching for getting-started/installation. It's a little hacky, but I couldn't get the docusaurus module for redirects to work right, but in the `pages/getting-started/` directory, there is a `.tsx` file for handling the installation redirect. others could be added if necessary with a slight modification of the url and the file name.

**Comment by Luap99** [comment]
> @Luap99 , I moved everything in the old site to live under the "old" directory to make sure that someone didn't merge something in that repo (github.com/containers/podman.io_old) and then accidentally have everything for the new page be overwritten when a PR was merged. I had hoped that all the pages would pop up under podman.io/old for easier reference/accessibility, but that failed and I've not had time to track that down yet.

I see, yeah this is not going to work AFAIK. Each repo can only have one domain. To achieve something like this you would need a reverse proxy that we can configure. Github pages basically just allows one domain per repo. Or you would need to copy all the old pages over to this repo here.

I think the best way if you want to keep the old site around would be add a `old.podman.io` domain to the old repo (and then just revert `old/` directory change there). This was users would be able to browse old.podman.io if necessary. 

---
@lilyx13 Thanks, redirect seems to work fine me so I going to close this issue then.
