### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by cdrage** [containers/podman.io#73]
Since it's Docusaurus, the search functionality should be enabled (you'll have to enable the API account as well). 

So it's easier to search for certain functionality such as Kubernetes docs, etc.

**Comment by lilyx13** [comment]
This is a great idea. I'll see about implementation after the maintainer meeting.

**Comment by lilyx13** [comment]
I followed up with Algolia and am awaiting the keys and snippits to add. @mairin if you like I can get it wired up still or pass on the instructions on how to do it.

**Comment by mairin** [comment]
@lilyx13 if you can pass on the instructions on how to do, that would be awsome @lilyx13

**Comment by lilyx13** [comment]
Yup I'll send you the API keys and instructions in the morning :)

**Comment by martsa1** [comment]
Not having search is a pretty frustrating experience if you're trying to find docs for something specific, hopefully you'll be able to enable this soon.

**Comment by cgiradkar** [comment]
The [RTD](https://about.readthedocs.com/) platform provides some rich features like automating the docs release process and maintaining and updating docs on a controlled frequency. Hence, the docs are hosted on the RTD website: [docs.podman.io](https://docs.podman.io). The website contains unabridged podman documentation and is integrated with the most useful search functionality.
FYI @mohanboddu @mairin
