### ISSUE TITLE
text not aligned on `formatted` blocks

### ISSUE THREAD

**Issue by benoitf** [containers/podman.io#76]
Trying https://podman.io/docs/introduction

at the bottom I can see
![image](https://github.com/containers/podman.io/assets/436777/7f9d5376-6252-4037-85b6-3c0f654b5dcf)

<code>text</code> looks like not vertically aligned properly

**Comment by lilyx13** [comment]
This seems to be related to how docusaurus renders in line code blocks. Perhaps in particular to when they are in a ul? I switched these out for bold commands for the time being so they still stand out.

**Comment by cgiradkar** [comment]
@TomSweeneyRedHat since docs have been shifted to docs.podman.io, the bug is irrelevant. watch: [Move to RTD](https://github.com/containers/podman.io/issues/73#issuecomment-1721502512).

**Comment by TomSweeneyRedHat** [comment]
Closing per last comment
