### ISSUE TITLE
images are not rendering in their original ratio

### ISSUE THREAD

**Issue by benoitf** [containers/podman.io#80]
on https://podman.io/features

Podman Command-Line commands images (like run, build, share, etc) are not rendered in their initial ratio so text is not looking nice

![image](https://github.com/containers/podman.io/assets/436777/29ba9a90-37cc-49f0-8c84-a157861c93af)

**Comment by mairin** [comment]
@lilyx13 this looks fixed to me, ok to close?
@benoitf do you still see the issue? i can't reproduce.

**Comment by benoitf** [comment]
@mairin it's ok for me I don't see anymore the issue
