### ISSUE TITLE
podman logo on documentation is not rendering correctly on dark theme

### ISSUE THREAD

**Issue by benoitf** [containers/podman.io#81]
![image](https://github.com/containers/podman.io/assets/436777/be649777-c0d4-4801-8b6d-635cd5254216)

I expect to have a light `man` at the end of `Podman`, here it is black/000000 color

**Comment by benoitf** [comment]
@lilyx13 https://docusaurus.io/docs/markdown-features/assets#themed-images

**Comment by mairin** [comment]
Thanks for the report! 🦭 🎉  The docusaurus docs link was very helpful 😀 Closing as fixed

![Screenshot from 2023-05-12 00-16-29](https://github.com/containers/podman.io/assets/799683/5e65b004-066d-44d6-bd7e-e6efdc66e2fc)
![Screenshot from 2023-05-12 00-16-25](https://github.com/containers/podman.io/assets/799683/ae5d5b9a-2feb-462c-a731-d1afda61c179)
