### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by benoitf** [containers/podman.io#83]
![image](https://github.com/containers/podman.io/assets/436777/95435e05-de52-4fb7-aa01-1737f89c9251)

It says Latest stable: 4.5.0 and the link of the Download for linux is 0.15.0

So few remarks:

- it's not clear to me that I'll download Podman Desktop  (Install on Desktop does not mean I'll install a Desktop tool)
- Probably version of the Desktop tool may be listed as well. So I would know that 0.15.0 is the Desktop version
- Maybe display icon of Podman Desktop when clicking on Download so I may be aware that I download Podman Desktop (instead of the penguin for Linux)

**Comment by lilyx13** [comment]
MM yeah I see the confusion here. do you think if we use `Install Desktop App v0.15` that it would be clearer, then with other Install options, specifically note the CLI and 4.5.0 there as well? @mairin do you have thoughts on this?

**Comment by benoitf** [comment]
it may help yes if the version is specified in the link title and what we'll get

**Comment by mairin** [comment]
@lilyx13 Ah yeh I'd put the Podman Desktop version first, then the Podman version since all the downloads we're pointing to are Podman Desktop.

**Comment by mairin** [comment]
Thanks for the report 🦭 🎉  - I have some changes pushed now that should help, and we'll take care of this more fully with issue #116.

![Screenshot from 2023-05-12 00-08-22](https://github.com/containers/podman.io/assets/799683/aa2a1e0f-a82b-45e5-82c6-4b2ae7343d99)
![Screenshot from 2023-05-12 00-07-59](https://github.com/containers/podman.io/assets/799683/c3e8ac64-cc90-409b-bf34-2a4c80c05845)
