### ISSUE TITLE
1px gap on most pages

### ISSUE THREAD

**Issue by deboer-tim** [containers/podman.io#84]
Except for the main page I see a 1px gap in the header:
<img width="848" alt="Screenshot 2023-05-09 at 10 20 23 AM" src="https://github.com/containers/podman.io/assets/19958075/265582c2-2cbb-4254-ba55-fb971c09d257">

**Comment by lilyx13** [comment]
I'm not seeing this on my screen but it might be a resolution issue. I just made a commit that should hopefully take care of this.

for some context, what screen resolution are you seeing this on?

**Comment by deboer-tim** [comment]
I'm seeing it in Safari on my 16" Mac M1, which I think is 3456x2234 pixels. I can't reproduce with Chrome, nor if I open the website in Safari on an external screen (I have an HD and a 4k monitor).

If I reproduce on the main screen and drag it to a monitor it fixes itself. Even if I then drag it back to the Mac screen it's still fine. :) So only on initial open on the M1 screen.
