### ISSUE TITLE
broken link for macOS download

### ISSUE THREAD

**Issue by benoitf** [containers/podman.io#89]
![image](https://github.com/containers/podman.io/assets/436777/f1a61fdd-0a39-4595-90be-cb29f8c0f6ec)

suggesting 
https://github.com/containers/podman-desktop/releases/download/v0.0.15.0/podman-desktop-0.0.15.0-universal.dmg

but working link is
 https://github.com/containers/podman-desktop/releases/download/v0.15.0/podman-desktop-0.15.0-universal.dmg

**Comment by mairin** [comment]
Closing as fixed, thanks for the report 😃
