### ISSUE TITLE
Investigating using containers/podman-docs as src for docusaurus on podman.io

### ISSUE THREAD

**Issue by mairin** [containers/podman.io#91]
Notes from maintainer meeting:

documentation on how docs "sync"? will docs be maintained in docs repo, then each release are built and copied over?

use stable docs

version docs

github actions / hook to move docs over to website repo

something to look at for inspiration:
ODO team has a script for release that moves docs over and versions them; could be done as a script that is run manually during releases

**Comment by lilyx13** [comment]
[this github action](https://github.com/marketplace/actions/push-a-file-to-another-repository) seems like it might be a good candidate for this sort of task.

**Comment by lilyx13** [comment]
This would be an interesting approach. However there are some issues with it that should be noted:
- auto generation without another script to organize and set page labels could result in messy docs
- it might add maintenance headaches down the road for customizing the docs using docusaurus' features.
- it adds a lot of extra steps to the build process

IMO, it'd be better to do a full migration that's had the time to be thought out, or to continue pointing to the docs.podman.io site for commands and the like, but keep with the current system (and consider expanding) the docusaurus docs as they seem to have a bit of a different focus.
